site_name: Grandma commands
site_author: pititiu
site_url: "https://pititu.github.io/Grandma.Help/"

theme:
  language: en
  name: material
  logo: assets/logo.png
  favicon: assets/logo.png
  features:
    - navigation.instant
    - navigation.sections
    - navigation.top
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.expand
    - navigation.indexes
    - navigation.tracking
    - header.autohide
    - content.tabs.link
    - search.suggest
    - search.highlight
    - search.share
  palette: 
    - scheme: default
      toggle:
        icon: material/toggle-switch-off-outline 
        name: Switch to dark mode
    - scheme: slate 
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode

    
markdown_extensions:
  - abbr
  - admonition
  - attr_list
  - def_list
  - footnotes
  - meta
  - pymdownx.details
  - toc:
      permalink: true
  - pymdownx.highlight
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.snippets
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.mark
  - pymdownx.tilde
  - pymdownx.smartsymbols

nav: 
  - Home: index.md
  - Bruteforce: bruteforce.md
  - Images: images.md
  - Information: information.md
  - Leet text: leet-text.md
  - Misc: misc.md
  - Moderation: 
    - Home: moderation.md
    - Prune: prune.md
  - Random: random.md
  - Remind: remind.md
  - Scripts:
    - Home: scripts.md
    - WIP:
      - Home: scripts-wip/index.md
      - Objects:
        - Channel: scripts-wip/objects/channel.md
        - Guild: scripts-wip/objects/guild.md
        - Member: scripts-wip/objects/member.md
        - User: scripts-wip/objects/user.md
        - Message: scripts-wip/objects/message.md
        - Role: scripts-wip/objects/role.md
        - Color: scripts-wip/objects/color.md
  - Time zone: time-zone.md
  - Discord tools: discord-tools.md
