name: docs

on:
  push:
    branches: [ main ]
    paths:
      - docs/**
      - mkdocs.yml
      - .github/workflows/docs.yml
  pull_request:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - name: Deploy docs
      uses: mhausenblas/mkdocs-deploy-gh-pages@master
      env:
        GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
